<a href="https://www.kaggle.com/code/youssefhatem1/xgboost-randomforest-smote?scriptVersionId=215759828" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [2]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import random
import plotly.express as px
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix


In [36]:
train_data1 = pd.read_csv(r'/kaggle/input/heartbeat/mitbih_train.csv',header=None)
train_data1.head()


0         1         2         3         4         5         6    \
0  0.977941  0.926471  0.681373  0.245098  0.154412  0.191176  0.151961   
1  0.960114  0.863248  0.461538  0.196581  0.094017  0.125356  0.099715   
2  1.000000  0.659459  0.186486  0.070270  0.070270  0.059459  0.056757   
3  0.925414  0.665746  0.541436  0.276243  0.196133  0.077348  0.071823   
4  0.967136  1.000000  0.830986  0.586854  0.356808  0.248826  0.145540   

        7         8         9    ...  178  179  180  181  182  183  184  185  \
0  0.085784  0.058824  0.049020  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
1  0.088319  0.074074  0.082621  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
2  0.043243  0.054054  0.045946  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
3  0.060773  0.066298  0.058011  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
4  0.089202  0.117371  0.150235  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

   186  187  
0  0.0  0.0  
1  0.0  0.0  
2  0.0  0.0  
3  0.0  0.0  
4  0.0  0.0  

[5 rows x 188 columns]

In [37]:
test_data1 = pd.read_csv(r'/kaggle/input/heartbeat/mitbih_test.csv',header=None)
test_data1.head()

0         1         2         3         4         5         6    \
0  1.000000  0.758264  0.111570  0.000000  0.080579  0.078512  0.066116   
1  0.908425  0.783883  0.531136  0.362637  0.366300  0.344322  0.333333   
2  0.730088  0.212389  0.000000  0.119469  0.101770  0.101770  0.110619   
3  1.000000  0.910417  0.681250  0.472917  0.229167  0.068750  0.000000   
4  0.570470  0.399329  0.238255  0.147651  0.000000  0.003356  0.040268   

        7         8         9    ...  178  179  180  181  182  183  184  185  \
0  0.049587  0.047521  0.035124  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
1  0.307692  0.296703  0.300366  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
2  0.123894  0.115044  0.132743  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
3  0.004167  0.014583  0.054167  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
4  0.080537  0.070470  0.090604  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

   186  187  
0  0.0  0.0  
1  0.0  0.0  
2  0.0  0.0  
3  0.0  0.0  
4  0.0  0.0  

[5 rows x 188 columns]

In [38]:
print(f"train data size: {train_data1.shape}")
print(f"test data size: {test_data1.shape}")

train data size: (87554, 188)
test data size: (21892, 188)


In [39]:
pd.set_option('display.max_rows', None)
print(train_data1.isna().sum())

0      0
1      0
2      0
3      0
4      0
5      0
6      0
7      0
8      0
9      0
10     0
11     0
12     0
13     0
14     0
15     0
16     0
17     0
18     0
19     0
20     0
21     0
22     0
23     0
24     0
25     0
26     0
27     0
28     0
29     0
30     0
31     0
32     0
33     0
34     0
35     0
36     0
37     0
38     0
39     0
40     0
41     0
42     0
43     0
44     0
45     0
46     0
47     0
48     0
49     0
50     0
51     0
52     0
53     0
54     0
55     0
56     0
57     0
58     0
59     0
60     0
61     0
62     0
63     0
64     0
65     0
66     0
67     0
68     0
69     0
70     0
71     0
72     0
73     0
74     0
75     0
76     0
77     0
78     0
79     0
80     0
81     0
82     0
83     0
84     0
85     0
86     0
87     0
88     0
89     0
90     0
91     0
92     0
93     0
94     0
95     0
96     0
97     0
98     0
99     0
100    0
101    0
102    0
103    0
104    0
105    0
106    0
107    0
108    0
109    0
110    0
1

In [40]:
from IPython.display import display

In [42]:
# See the number of each class in train dataset
labels = {
    0: "Normal",
    1: "Artial Premature",
    2: "Premature ventricular contraction",
    3: "Fusion of ventricular and normal",
    4: "Fusion of paced and normal"
}


value_counts = train_data1.iloc[:,-1].value_counts().rename(labels)

pie_fig = px.pie(names=value_counts.index, values=value_counts.values,
                 title="The Percentage of Each Label in The Train Dataset")

pie_fig.update_layout(title_x=0.5, width=800, height=600)
pie_fig.show()

In [43]:
# See the number of each class in test dataset
value_counts_test = test_data1.iloc[:,-1].value_counts().rename(labels)

pie_fig = px.pie(names=value_counts_test.index, values=value_counts_test.values,
                 title="The Percentage of Each Label in The Test Dataset")

pie_fig.update_layout(title_x=0.5, width=800, height=600)
pie_fig.show()

In [44]:
train_data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 87554 entries, 0 to 87553
Columns: 188 entries, 0 to 187
dtypes: float64(188)
memory usage: 125.6 MB


In [45]:
#show max value for each column
max_values = train_data1.max()
print(max_values)

0      1.0
1      1.0
2      1.0
3      1.0
4      1.0
5      1.0
6      1.0
7      1.0
8      1.0
9      1.0
10     1.0
11     1.0
12     1.0
13     1.0
14     1.0
15     1.0
16     1.0
17     1.0
18     1.0
19     1.0
20     1.0
21     1.0
22     1.0
23     1.0
24     1.0
25     1.0
26     1.0
27     1.0
28     1.0
29     1.0
30     1.0
31     1.0
32     1.0
33     1.0
34     1.0
35     1.0
36     1.0
37     1.0
38     1.0
39     1.0
40     1.0
41     1.0
42     1.0
43     1.0
44     1.0
45     1.0
46     1.0
47     1.0
48     1.0
49     1.0
50     1.0
51     1.0
52     1.0
53     1.0
54     1.0
55     1.0
56     1.0
57     1.0
58     1.0
59     1.0
60     1.0
61     1.0
62     1.0
63     1.0
64     1.0
65     1.0
66     1.0
67     1.0
68     1.0
69     1.0
70     1.0
71     1.0
72     1.0
73     1.0
74     1.0
75     1.0
76     1.0
77     1.0
78     1.0
79     1.0
80     1.0
81     1.0
82     1.0
83     1.0
84     1.0
85     1.0
86     1.0
87     1.0
88     1.0
89     1.0
90     1.0

In [46]:
#split train_data to x_train and _y_train
# Split the data into features (X_train) and target (y_train)
X_train1 = train_data1.iloc[:, :-1]  # All columns except the last one
y_train1 = train_data1.iloc[:, -1]   # Only the last column

# Display the shapes to confirm the split
print("Shape of X_train:", X_train1.shape)
print("Shape of y_train:", y_train1.shape)


Shape of X_train: (87554, 187)
Shape of y_train: (87554,)


In [48]:
# Step 2: Apply SMOTE
from imblearn.over_sampling import SMOTE
smote = SMOTE(random_state=42)  # Initialize SMOTE
X_resampled, y_resampled = smote.fit_resample(X_train1, y_train1)  # Resample the data

In [49]:
# See the number of each class in Train dataset
value_counts_test = y_resampled.value_counts().rename(labels)

pie_fig = px.pie(names=value_counts_test.index, values=value_counts_test.values,
                 title="The Percentage of Each Label in The Test Dataset")

pie_fig.update_layout(title_x=0.5, width=800, height=600)
pie_fig.show()

In [50]:
#Train model using Logistic Regression
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

# Step 3: Split the data into training and testing sets
X_train1,X_test1, y_train1, y_test1 = train_test_split(X_resampled, y_resampled, test_size=0.2, random_state=42)
# Step 4: Train the Logistic Regression model
model1 = LogisticRegression()
model1.fit(X_train1, y_train1)
# Step 5: Make predictions on the test set
y_pred1 = model1.predict(X_test1)

# Step 6: Evaluate the model
accuracy1 = accuracy_score(y_test1, y_pred1)
print(f'Accuracy: {accuracy1 * 100:.2f}%')
print('Classification Report:')
print(classification_report(y_test1, y_pred1))

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning:

lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression



Accuracy: 78.60%
Classification Report:
              precision    recall  f1-score   support

         0.0       0.62      0.61      0.61     14462
         1.0       0.81      0.75      0.78     14535
         2.0       0.74      0.79      0.76     14419
         3.0       0.83      0.87      0.85     14432
         4.0       0.93      0.92      0.93     14623

    accuracy                           0.79     72471
   macro avg       0.79      0.79      0.79     72471
weighted avg       0.79      0.79      0.79     72471



In [51]:
import xgboost as xgb
from sklearn.metrics import accuracy_score, classification_report
from sklearn.model_selection import train_test_split

# Step 3: Split the data into training and testing sets
X_train2, X_test2, y_train2, y_test2 = train_test_split(X_resampled, y_resampled, test_size=0.2, random_state=42)

# Step 4: Train the XGBoost model
model2 = xgb.XGBClassifier(random_state=42, use_label_encoder=False, eval_metric='mlogloss')
model2.fit(X_train2, y_train2)

# Step 5: Make predictions on the test set
y_pred2 = model2.predict(X_test2)

# Step 6: Evaluate the model
accuracy2 = accuracy_score(y_test2, y_pred2)
print(f'Accuracy: {accuracy2 * 100:.2f}%')
print('Classification Report:')
print(classification_report(y_test2, y_pred2))


Accuracy: 99.15%
Classification Report:
              precision    recall  f1-score   support

         0.0       0.99      0.98      0.98     14462
         1.0       0.99      0.99      0.99     14535
         2.0       0.99      0.99      0.99     14419
         3.0       0.99      1.00      1.00     14432
         4.0       1.00      1.00      1.00     14623

    accuracy                           0.99     72471
   macro avg       0.99      0.99      0.99     72471
weighted avg       0.99      0.99      0.99     72471



In [52]:
####run model on test_data###

# Features (X) and target (y)
X1 = test_data1.drop(187, axis=1)  # Replace 'target' with your target column name
y1 = test_data1[187]  # Replace 'target' with your target column name


In [53]:
X1.shape

(21892, 187)

In [54]:
# Step 5: Make predictions on the test set
y_pred_test_1 = model2.predict(X1)

# Step 6: Evaluate the model
accuracy2 = accuracy_score(y1, y_pred_test_1)
print(f'Accuracy For XGBoost Model After resampling: {accuracy2 * 100:.2f}%')
print('Classification Report For XGBoost Model After resampling :')
print(classification_report(y1, y_pred_test_1))


Accuracy For XGBoost Model After resampling: 96.78%
Classification Report For XGBoost Model After resampling :
              precision    recall  f1-score   support

         0.0       0.99      0.98      0.98     18118
         1.0       0.61      0.80      0.69       556
         2.0       0.93      0.94      0.94      1448
         3.0       0.59      0.85      0.70       162
         4.0       0.98      0.98      0.98      1608

    accuracy                           0.97     21892
   macro avg       0.82      0.91      0.86     21892
weighted avg       0.97      0.97      0.97     21892



In [55]:
Data_Abnormal = pd.read_csv(r'/kaggle/input/heartbeat/ptbdb_abnormal.csv',header=None)
Data_Abnormal.head()


0         1         2         3         4         5         6    \
0  0.932233  0.869679  0.886186  0.929626  0.908775  0.933970  0.801043   
1  1.000000  0.606941  0.384181  0.254237  0.223567  0.276836  0.253430   
2  1.000000  0.951613  0.923963  0.853303  0.791859  0.734255  0.672043   
3  0.977819  0.899261  0.230129  0.032348  0.142329  0.223660  0.328096   
4  0.935618  0.801661  0.805815  1.000000  0.722741  0.480789  0.454829   

        7         8         9    ...  178  179  180  181  182  183  184  185  \
0  0.749783  0.687229  0.635100  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
1  0.184826  0.153349  0.121872  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
2  0.685100  0.670507  0.667435  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
3  0.367837  0.381701  0.389094  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
4  0.319834  0.266874  0.308411  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

   186  187  
0  0.0  1.0  
1  0.0  1.0  
2  0.0  1.0  
3  0.0  1.0  
4  0.0  1.0  

[5 rows x 188 columns]

In [56]:
Data_Abnormal.shape

(10506, 188)

In [57]:
Data_Normal = pd.read_csv(r'//kaggle/input/heartbeat/ptbdb_normal.csv',header=None)
Data_Normal.head()


0         1         2         3         4         5         6    \
0  1.000000  0.900324  0.358590  0.051459  0.046596  0.126823  0.133306   
1  1.000000  0.794681  0.375387  0.116883  0.000000  0.171923  0.283859   
2  0.909029  0.791482  0.423169  0.186712  0.000000  0.007836  0.063032   
3  1.000000  0.478893  0.056760  0.064176  0.081289  0.072732  0.055619   
4  1.000000  0.867238  0.201360  0.099349  0.141336  0.120934  0.108516   

        7         8         9    ...  178  179  180  181  182  183  184  185  \
0  0.119125  0.110616  0.113047  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
1  0.293754  0.325912  0.345083  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
2  0.077002  0.074957  0.077342  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
3  0.048774  0.054478  0.041643  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
4  0.096393  0.093436  0.100828  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

   186  187  
0  0.0  0.0  
1  0.0  0.0  
2  0.0  0.0  
3  0.0  0.0  
4  0.0  0.0  

[5 rows x 188 columns]

In [58]:
Data_Normal.shape

(4046, 188)

In [59]:
#Concatenate tow datasets 
import pandas as pd

# Concatenate the datasets along rows (vertically)
concatenated_data = pd.concat([Data_Normal, Data_Abnormal], axis=0, ignore_index=True)

# Check the result
concatenated_data.head()


0         1         2         3         4         5         6    \
0  1.000000  0.900324  0.358590  0.051459  0.046596  0.126823  0.133306   
1  1.000000  0.794681  0.375387  0.116883  0.000000  0.171923  0.283859   
2  0.909029  0.791482  0.423169  0.186712  0.000000  0.007836  0.063032   
3  1.000000  0.478893  0.056760  0.064176  0.081289  0.072732  0.055619   
4  1.000000  0.867238  0.201360  0.099349  0.141336  0.120934  0.108516   

        7         8         9    ...  178  179  180  181  182  183  184  185  \
0  0.119125  0.110616  0.113047  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
1  0.293754  0.325912  0.345083  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
2  0.077002  0.074957  0.077342  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
3  0.048774  0.054478  0.041643  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
4  0.096393  0.093436  0.100828  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

   186  187  
0  0.0  0.0  
1  0.0  0.0  
2  0.0  0.0  
3  0.0  0.0  
4  0.0  0.0  

[5 rows x 188 columns]

In [60]:
concatenated_data.shape

(14552, 188)

In [61]:
# Shuffle the concatenated_data dataset
concatenated_data = concatenated_data.sample(frac=1, random_state=42).reset_index(drop=True)


In [62]:
# Show Unique values in Last Column
unique_values = concatenated_data.iloc[:, -1].unique()
unique_values

array([0., 1.])

In [63]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Step 1: Prepare features (X) and target (y)
X3 = concatenated_data.drop(187, axis=1)  # Replace '187' with the column index or name to remove target column
y3 = concatenated_data[187]  # Replace '187' with the column index or name for the target (Normal or Abnormal)

# Step 2: Split the data into training and testing sets
X_train3, X_test3, y_train3, y_test3 = train_test_split(X3, y3, test_size=0.2, random_state=42)

# Step 3: Train the Random Forest model
model3 = RandomForestClassifier(random_state=42)  # You can adjust parameters like n_estimators, max_depth, etc.
model3.fit(X_train3, y_train3)

# Step 4: Make predictions
y_pred3 = model3.predict(X_test3)

# Step 5: Evaluate the model
accuracy3 = accuracy_score(y_test3, y_pred3)
print(f'Accuracy For Binary Classfication Model: {accuracy3 * 100:.2f}%')

print('Classification Report For Binary Classfication Model:')
print(classification_report(y_test3, y_pred3))

print('Confusion Matrix For Binary Calssification :')
print(confusion_matrix(y_test3, y_pred3))


Accuracy For Binary Classfication Model: 97.22%
Classification Report For Binary Classfication Model:
              precision    recall  f1-score   support

         0.0       0.98      0.92      0.95       805
         1.0       0.97      0.99      0.98      2106

    accuracy                           0.97      2911
   macro avg       0.97      0.96      0.96      2911
weighted avg       0.97      0.97      0.97      2911

Confusion Matrix For Binary Calssification :
[[ 743   62]
 [  19 2087]]


In [64]:
# Get unique values
unique_values_2 = np.unique(y_pred3)
unique_values_2

array([0., 1.])

In [65]:
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Step 1: Prepare features (X) and target (y)
X4 = concatenated_data.drop(187, axis=1)  # Replace '187' with the column index or name to remove target column
y4 = concatenated_data[187]  # Replace '187' with the column index or name for the target (Normal or Abnormal)

# Step 2: Split the data into training and testing sets
X_train4, X_test4, y_train4, y_test4 = train_test_split(X4, y4, test_size=0.2, random_state=42)

# Step 3: Train the XGBoost model
model4 = xgb.XGBClassifier(random_state=42, use_label_encoder=False, eval_metric='mlogloss')  # Adding `use_label_encoder=False` to avoid warnings
model4.fit(X_train4, y_train4)

# Step 4: Make predictions
y_pred4 = model4.predict(X_test4)

# Step 5: Evaluate the model
accuracy4 = accuracy_score(y_test4, y_pred4)
print(f'Accuracy For Binary Classfication Model using XGBoost: {accuracy4 * 100:.2f}%')

print('Classification Report For Binary Classfication Model using XGBoost :')
print(classification_report(y_test4, y_pred4))

print('Confusion Matrix For Binary Classfication Model using XGBoost:')
print(confusion_matrix(y_test4, y_pred4))


Accuracy For Binary Classfication Model using XGBoost: 97.97%
Classification Report For Binary Classfication Model using XGBoost :
              precision    recall  f1-score   support

         0.0       0.97      0.96      0.96       805
         1.0       0.98      0.99      0.99      2106

    accuracy                           0.98      2911
   macro avg       0.98      0.97      0.97      2911
weighted avg       0.98      0.98      0.98      2911

Confusion Matrix For Binary Classfication Model using XGBoost:
[[ 769   36]
 [  23 2083]]


In [66]:
# Check if the last column's value is 0 or not
test_data1['Normal_or_Abnormal'] = test_data1.iloc[:, -1].apply(lambda x: 0 if x == 0 else 1)

In [67]:
test_data1.head()

0         1         2         3         4         5         6  \
0  1.000000  0.758264  0.111570  0.000000  0.080579  0.078512  0.066116   
1  0.908425  0.783883  0.531136  0.362637  0.366300  0.344322  0.333333   
2  0.730088  0.212389  0.000000  0.119469  0.101770  0.101770  0.110619   
3  1.000000  0.910417  0.681250  0.472917  0.229167  0.068750  0.000000   
4  0.570470  0.399329  0.238255  0.147651  0.000000  0.003356  0.040268   

          7         8         9  ...  179  180  181  182  183  184  185  186  \
0  0.049587  0.047521  0.035124  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
1  0.307692  0.296703  0.300366  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
2  0.123894  0.115044  0.132743  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
3  0.004167  0.014583  0.054167  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
4  0.080537  0.070470  0.090604  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

   187  Normal_or_Abnormal  
0  0.0                   0  
1  0.0                   0  
2  0.0                   0  
3  0.0                   0  
4  0.0                   0  

[5 rows x 189 columns]

In [68]:
# Step 4: Make predictions
X_test_features = test_data1.iloc[:, :-2]  # Drop the last two columns for predictions
y_pred_Test = model4.predict(X_test_features)

# Step 5: Evaluate the model
# Use the actual target column (last column) for evaluation
y_true = test_data1.iloc[:, -1]  # Last column as ground truth

# Evaluate the accuracy
accuracy6 = accuracy_score(y_true, y_pred_Test)
print(f'Accuracy For Binary Classification Model using XGBoost On Test Data: {accuracy6 * 100:.2f}%')

# Print classification report
print('Classification Report For Binary Classification Model using XGBoost On Test Data:')
print(classification_report(y_true, y_pred_Test))

# Print confusion matrix
print('Confusion Matrix For Binary Classification Model using XGBoost On Test Data:')
print(confusion_matrix(y_true, y_pred_Test))


Accuracy For Binary Classification Model using XGBoost On Test Data: 26.35%
Classification Report For Binary Classification Model using XGBoost On Test Data:
              precision    recall  f1-score   support

           0       0.93      0.12      0.21     18118
           1       0.18      0.96      0.31      3774

    accuracy                           0.26     21892
   macro avg       0.56      0.54      0.26     21892
weighted avg       0.80      0.26      0.23     21892

Confusion Matrix For Binary Classification Model using XGBoost On Test Data:
[[ 2158 15960]
 [  163  3611]]


In [69]:
# Get unique values
unique_values_3 = np.unique(y_pred4)
unique_values_3

array([0, 1])

****For Ab Normal Classes****

In [70]:
train_data2 = pd.read_csv(r'/kaggle/input/heartbeat/mitbih_train.csv',header=None)
train_data2.head()

0         1         2         3         4         5         6    \
0  0.977941  0.926471  0.681373  0.245098  0.154412  0.191176  0.151961   
1  0.960114  0.863248  0.461538  0.196581  0.094017  0.125356  0.099715   
2  1.000000  0.659459  0.186486  0.070270  0.070270  0.059459  0.056757   
3  0.925414  0.665746  0.541436  0.276243  0.196133  0.077348  0.071823   
4  0.967136  1.000000  0.830986  0.586854  0.356808  0.248826  0.145540   

        7         8         9    ...  178  179  180  181  182  183  184  185  \
0  0.085784  0.058824  0.049020  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
1  0.088319  0.074074  0.082621  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
2  0.043243  0.054054  0.045946  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
3  0.060773  0.066298  0.058011  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
4  0.089202  0.117371  0.150235  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

   186  187  
0  0.0  0.0  
1  0.0  0.0  
2  0.0  0.0  
3  0.0  0.0  
4  0.0  0.0  

[5 rows x 188 columns]

In [71]:
test_data2 = pd.read_csv(r'/kaggle/input/heartbeat/mitbih_test.csv',header=None)
test_data2.head()

0         1         2         3         4         5         6    \
0  1.000000  0.758264  0.111570  0.000000  0.080579  0.078512  0.066116   
1  0.908425  0.783883  0.531136  0.362637  0.366300  0.344322  0.333333   
2  0.730088  0.212389  0.000000  0.119469  0.101770  0.101770  0.110619   
3  1.000000  0.910417  0.681250  0.472917  0.229167  0.068750  0.000000   
4  0.570470  0.399329  0.238255  0.147651  0.000000  0.003356  0.040268   

        7         8         9    ...  178  179  180  181  182  183  184  185  \
0  0.049587  0.047521  0.035124  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
1  0.307692  0.296703  0.300366  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
2  0.123894  0.115044  0.132743  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
3  0.004167  0.014583  0.054167  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
4  0.080537  0.070470  0.090604  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

   186  187  
0  0.0  0.0  
1  0.0  0.0  
2  0.0  0.0  
3  0.0  0.0  
4  0.0  0.0  

[5 rows x 188 columns]

In [72]:
print(f"train data size: {train_data2.shape}")
print(f"test data size: {test_data2.shape}")

train data size: (87554, 188)
test data size: (21892, 188)


In [73]:
from IPython.display import display

In [74]:
# See the number of each class in train dataset
labels = {
    0: "Normal",
    1: "Artial Premature",
    2: "Premature ventricular contraction",
    3: "Fusion of ventricular and normal",
    4: "Fusion of paced and normal"
}


value_counts = train_data2.iloc[:,-1].value_counts().rename(labels)

pie_fig = px.pie(names=value_counts.index, values=value_counts.values,
                 title="The Percentage of Each Label in The Train Dataset")

pie_fig.update_layout(title_x=0.5, width=800, height=600)
pie_fig.show()

In [75]:
# See the number of each class in test dataset
value_counts_test = test_data2.iloc[:,-1].value_counts().rename(labels)

pie_fig = px.pie(names=value_counts_test.index, values=value_counts_test.values,
                 title="The Percentage of Each Label in The Test Dataset")

pie_fig.update_layout(title_x=0.5, width=800, height=600)
pie_fig.show()

In [76]:
train_data2.head()

0         1         2         3         4         5         6    \
0  0.977941  0.926471  0.681373  0.245098  0.154412  0.191176  0.151961   
1  0.960114  0.863248  0.461538  0.196581  0.094017  0.125356  0.099715   
2  1.000000  0.659459  0.186486  0.070270  0.070270  0.059459  0.056757   
3  0.925414  0.665746  0.541436  0.276243  0.196133  0.077348  0.071823   
4  0.967136  1.000000  0.830986  0.586854  0.356808  0.248826  0.145540   

        7         8         9    ...  178  179  180  181  182  183  184  185  \
0  0.085784  0.058824  0.049020  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
1  0.088319  0.074074  0.082621  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
2  0.043243  0.054054  0.045946  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
3  0.060773  0.066298  0.058011  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
4  0.089202  0.117371  0.150235  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

   186  187  
0  0.0  0.0  
1  0.0  0.0  
2  0.0  0.0  
3  0.0  0.0  
4  0.0  0.0  

[5 rows x 188 columns]

In [77]:
#Fiter data git data without class 0 who in feature 187
filtered_data1 = train_data2[train_data2[187] != 0]

# Display the filtered data
filtered_data1.head()

0         1         2         3         4         5         6    \
72471  1.000000  0.666667  0.100457  0.036530  0.073059  0.050228  0.018265   
72472  0.983696  1.000000  0.331522  0.000000  0.108696  0.163043  0.130435   
72473  1.000000  0.911504  0.216814  0.000000  0.101770  0.199115  0.176991   
72474  0.090498  0.126697  0.217195  0.361991  0.461538  0.556561  0.443439   
72475  0.961111  1.000000  0.551852  0.101852  0.040741  0.085185  0.094444   

            7         8         9    ...       178       179       180  \
72471  0.105023  0.132420  0.091324  ...  0.000000  0.000000  0.000000   
72472  0.190217  0.288043  0.222826  ...  0.461957  0.483696  0.500000   
72473  0.194690  0.252212  0.238938  ...  0.000000  0.000000  0.000000   
72474  0.434389  0.452489  0.511312  ...  0.122172  0.131222  0.140271   
72475  0.088889  0.085185  0.070370  ...  0.000000  0.000000  0.000000   

            181       182      183       184       185       186  187  
72471  0.000000  0.000000  0.00000  0.000000  0.000000  0.000000  1.0  
72472  0.494565  0.510870  0.51087  0.505435  0.472826  0.434783  1.0  
72473  0.000000  0.000000  0.00000  0.000000  0.000000  0.000000  1.0  
72474  0.158371  0.176471  0.20362  0.212670  0.000000  0.000000  1.0  
72475  0.000000  0.000000  0.00000  0.000000  0.000000  0.000000  1.0  

[5 rows x 188 columns]

In [78]:
# Get unique values in column 187 of the filtered_data
unique_values4 = filtered_data1.iloc[:, 187].unique()

In [79]:
unique_values4

array([1., 2., 3., 4.])

In [80]:
value_counts = filtered_data1.iloc[:,-1].value_counts().rename(labels)

pie_fig = px.pie(names=value_counts.index, values=value_counts.values,
                 title="The Percentage of Each Label in The Train Dataset")

pie_fig.update_layout(title_x=0.5, width=800, height=600)
pie_fig.show()

In [81]:
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Step 1: Adjust the target variable (y) to start from 0
y5 = filtered_data1[187] - 1  # Subtract 1 to shift labels to start from 0

# Step 2: Prepare features (X)
X5 = filtered_data1.drop(187, axis=1)  # Remove the target column

# Step 3: Split the data into training and testing sets
X_train5, X_test5, y_train5, y_test5 = train_test_split(X5, y5, test_size=0.2, random_state=42)

# Step 4: Train the XGBoost model
model5 = xgb.XGBClassifier(random_state=42, use_label_encoder=False, eval_metric='mlogloss')  # Avoiding warnings
model5.fit(X_train5, y_train5)

# Step 5: Make predictions
y_pred5 = model5.predict(X_test5)

# Step 6: Evaluate the model
accuracy5 = accuracy_score(y_test5, y_pred5)
print(f'Accuracy For AbNormal Classes Using XGBoost: {accuracy5 * 100:.2f}%')

print('Classification Report For AbNormal Classes Using XGBoost:')
print(classification_report(y_test5, y_pred5))

print('Confusion Matrix For AbNormal Classes Using XGBoost:')
print(confusion_matrix(y_test5, y_pred5))


Accuracy For AbNormal Classes Using XGBoost: 97.65%
Classification Report For AbNormal Classes Using XGBoost:
              precision    recall  f1-score   support

         0.0       0.96      0.96      0.96       442
         1.0       0.97      0.98      0.98      1181
         2.0       0.97      0.88      0.92       143
         3.0       0.99      0.99      0.99      1251

    accuracy                           0.98      3017
   macro avg       0.97      0.95      0.96      3017
weighted avg       0.98      0.98      0.98      3017

Confusion Matrix For AbNormal Classes Using XGBoost:
[[ 424   12    0    6]
 [   7 1163    4    7]
 [   5   12  126    0]
 [   5   13    0 1233]]


In [82]:
test_data2.head()

0         1         2         3         4         5         6    \
0  1.000000  0.758264  0.111570  0.000000  0.080579  0.078512  0.066116   
1  0.908425  0.783883  0.531136  0.362637  0.366300  0.344322  0.333333   
2  0.730088  0.212389  0.000000  0.119469  0.101770  0.101770  0.110619   
3  1.000000  0.910417  0.681250  0.472917  0.229167  0.068750  0.000000   
4  0.570470  0.399329  0.238255  0.147651  0.000000  0.003356  0.040268   

        7         8         9    ...  178  179  180  181  182  183  184  185  \
0  0.049587  0.047521  0.035124  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
1  0.307692  0.296703  0.300366  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
2  0.123894  0.115044  0.132743  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
3  0.004167  0.014583  0.054167  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
4  0.080537  0.070470  0.090604  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

   186  187  
0  0.0  0.0  
1  0.0  0.0  
2  0.0  0.0  
3  0.0  0.0  
4  0.0  0.0  

[5 rows x 188 columns]

In [83]:
test_data2.shape

(21892, 188)

In [84]:
X_test2_without_last_column = test_data2.drop(test_data2.columns[-1], axis=1) 
y_pred6 = model4.predict(X_test2_without_last_column)

test_data2['Ab_or_Not'] = y_pred6

test_data2.head()

0         1         2         3         4         5         6  \
0  1.000000  0.758264  0.111570  0.000000  0.080579  0.078512  0.066116   
1  0.908425  0.783883  0.531136  0.362637  0.366300  0.344322  0.333333   
2  0.730088  0.212389  0.000000  0.119469  0.101770  0.101770  0.110619   
3  1.000000  0.910417  0.681250  0.472917  0.229167  0.068750  0.000000   
4  0.570470  0.399329  0.238255  0.147651  0.000000  0.003356  0.040268   

          7         8         9  ...  179  180  181  182  183  184  185  186  \
0  0.049587  0.047521  0.035124  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
1  0.307692  0.296703  0.300366  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
2  0.123894  0.115044  0.132743  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
3  0.004167  0.014583  0.054167  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
4  0.080537  0.070470  0.090604  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

   187  Ab_or_Not  
0  0.0          0  
1  0.0          1  
2  0.0          1  
3  0.0          1  
4  0.0          1  

[5 rows x 189 columns]

In [85]:
test_data2['Ab_or_Not'].unique()

array([0, 1])

# Here I start to Solve problem That normal and abnormal data not generalize in testing

In [3]:
train_data3 = pd.read_csv(r'/kaggle/input/heartbeat/mitbih_train.csv',header=None)
train_data3.head()

0         1         2         3         4         5         6    \
0  0.977941  0.926471  0.681373  0.245098  0.154412  0.191176  0.151961   
1  0.960114  0.863248  0.461538  0.196581  0.094017  0.125356  0.099715   
2  1.000000  0.659459  0.186486  0.070270  0.070270  0.059459  0.056757   
3  0.925414  0.665746  0.541436  0.276243  0.196133  0.077348  0.071823   
4  0.967136  1.000000  0.830986  0.586854  0.356808  0.248826  0.145540   

        7         8         9    ...  178  179  180  181  182  183  184  185  \
0  0.085784  0.058824  0.049020  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
1  0.088319  0.074074  0.082621  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
2  0.043243  0.054054  0.045946  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
3  0.060773  0.066298  0.058011  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
4  0.089202  0.117371  0.150235  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

   186  187  
0  0.0  0.0  
1  0.0  0.0  
2  0.0  0.0  
3  0.0  0.0  
4  0.0  0.0  

[5 rows x 188 columns]

In [4]:
test_data3 = pd.read_csv(r'/kaggle/input/heartbeat/mitbih_test.csv',header=None)
test_data3.head()

0         1         2         3         4         5         6    \
0  1.000000  0.758264  0.111570  0.000000  0.080579  0.078512  0.066116   
1  0.908425  0.783883  0.531136  0.362637  0.366300  0.344322  0.333333   
2  0.730088  0.212389  0.000000  0.119469  0.101770  0.101770  0.110619   
3  1.000000  0.910417  0.681250  0.472917  0.229167  0.068750  0.000000   
4  0.570470  0.399329  0.238255  0.147651  0.000000  0.003356  0.040268   

        7         8         9    ...  178  179  180  181  182  183  184  185  \
0  0.049587  0.047521  0.035124  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
1  0.307692  0.296703  0.300366  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
2  0.123894  0.115044  0.132743  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
3  0.004167  0.014583  0.054167  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
4  0.080537  0.070470  0.090604  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

   186  187  
0  0.0  0.0  
1  0.0  0.0  
2  0.0  0.0  
3  0.0  0.0  
4  0.0  0.0  

[5 rows x 188 columns]

**Work For Binary Classification Model in train**

In [5]:
# Check if the last column's value is 0 or not
train_data3['Normal_or_Abnormal'] = train_data3.iloc[:, -1].apply(lambda x: 0 if x == 0 else 1)


In [6]:
#Drop Column 187
train_data3.drop(columns=187, inplace=True)

In [7]:
train_data3.head()

0         1         2         3         4         5         6  \
0  0.977941  0.926471  0.681373  0.245098  0.154412  0.191176  0.151961   
1  0.960114  0.863248  0.461538  0.196581  0.094017  0.125356  0.099715   
2  1.000000  0.659459  0.186486  0.070270  0.070270  0.059459  0.056757   
3  0.925414  0.665746  0.541436  0.276243  0.196133  0.077348  0.071823   
4  0.967136  1.000000  0.830986  0.586854  0.356808  0.248826  0.145540   

          7         8         9  ...  178  179  180  181  182  183  184  185  \
0  0.085784  0.058824  0.049020  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
1  0.088319  0.074074  0.082621  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
2  0.043243  0.054054  0.045946  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
3  0.060773  0.066298  0.058011  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
4  0.089202  0.117371  0.150235  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

   186  Normal_or_Abnormal  
0  0.0                   0  
1  0.0                   0  
2  0.0                   0  
3  0.0                   0  
4  0.0                   0  

[5 rows x 188 columns]

In [8]:
#Count for Each class in column Normal_or_Abnormal
class_counts = train_data3['Normal_or_Abnormal'].value_counts()

# Display the counts
class_counts

Normal_or_Abnormal
0    72471
1    15083
Name: count, dtype: int64

In [114]:
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Step 1: Prepare features (X) and target (y)
X6 = train_data3.drop('Normal_or_Abnormal', axis=1)  # Replace with the appropriate column name
y6 = train_data3['Normal_or_Abnormal']

# Step 2: Split the data into training and testing sets
X_train6, X_test6, y_train6, y_test6 = train_test_split(X6, y6, test_size=0.2, random_state=42)

# Step 2: Apply SMOTE
from imblearn.over_sampling import SMOTE
smote = SMOTE(random_state=42)  # Initialize SMOTE
X_train6, y_train6 = smote.fit_resample(X_train6, y_train6)  # Resample the data

# Step 3: Calculate the scale_pos_weight
# Number of samples in class 1 / Number of samples in class 0
class_0_count = (y_train6 == 0).sum()
class_1_count = (y_train6 == 1).sum()
ratio = class_0_count / class_1_count

# Step 4: Train the XGBoost model with scale_pos_weight
model6 = xgb.XGBClassifier(
    random_state=42, 
    use_label_encoder=False, 
    eval_metric='mlogloss', 
    scale_pos_weight=ratio  # Adjusting the weight of classes
)
model6.fit(X_train6, y_train6)

# Step 5: Make predictions
y_pred6 = model6.predict(X_test6)

# Step 6: Evaluate the model
accuracy6 = accuracy_score(y_test6, y_pred6)
print(f'Accuracy For Binary Classification Model using XGBoost: {accuracy6 * 100:.2f}%')

print('Classification Report:')
print(classification_report(y_test6, y_pred6))

print('Confusion Matrix:')
print(confusion_matrix(y_test6, y_pred6))

# Save the model
joblib.dump(model6, '/kaggle/working/xgboost_BinaryClasses_model.pkl')

print("Model saved as 'xgboost_model.pkl' in /kaggle/working/")



Accuracy For Binary Classification Model using XGBoost: 97.88%
Classification Report:
              precision    recall  f1-score   support

           0       0.99      0.99      0.99     14579
           1       0.94      0.94      0.94      2932

    accuracy                           0.98     17511
   macro avg       0.96      0.96      0.96     17511
weighted avg       0.98      0.98      0.98     17511

Confusion Matrix:
[[14394   185]
 [  186  2746]]
Model saved as 'xgboost_model.pkl' in /kaggle/working/


In [115]:
# Check if the last column's value is 0 or not
test_data3['Normal_or_Abnormal'] = test_data3.iloc[:, -1].apply(lambda x: 0 if x == 0 else 1)

In [ ]:
#Drop Column 187
test_data3.drop(columns=187, inplace=True)

In [116]:
test_data3.head()

0         1         2         3         4         5         6  \
0  1.000000  0.758264  0.111570  0.000000  0.080579  0.078512  0.066116   
1  0.908425  0.783883  0.531136  0.362637  0.366300  0.344322  0.333333   
2  0.730088  0.212389  0.000000  0.119469  0.101770  0.101770  0.110619   
3  1.000000  0.910417  0.681250  0.472917  0.229167  0.068750  0.000000   
4  0.570470  0.399329  0.238255  0.147651  0.000000  0.003356  0.040268   

          7         8         9  ...  178  179  180  181  182  183  184  185  \
0  0.049587  0.047521  0.035124  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
1  0.307692  0.296703  0.300366  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
2  0.123894  0.115044  0.132743  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
3  0.004167  0.014583  0.054167  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
4  0.080537  0.070470  0.090604  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

   186  Normal_or_Abnormal  
0  0.0                   0  
1  0.0                   0  
2  0.0                   0  
3  0.0                   0  
4  0.0                   0  

[5 rows x 188 columns]

In [117]:
test_data3.shape

(21892, 188)

In [118]:
#Count for Each class in column Normal_or_Abnormal
class_counts = test_data3['Normal_or_Abnormal'].value_counts()

# Display the counts
class_counts

Normal_or_Abnormal
0    18118
1     3774
Name: count, dtype: int64

In [119]:
import joblib
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Step 1: Load the trained model from the .pkl file
model6 = joblib.load('/kaggle/working/xgboost_BinaryClasses_model.pkl')  # Replace with the correct path to your model


# Step 2: Prepare features (X) and target (y)
X6_test = test_data3.drop('Normal_or_Abnormal', axis=1)  # Replace with the appropriate column name
y6_test = test_data3['Normal_or_Abnormal']

# Step 3: Make predictions
y_pred6_test = model6.predict(X6_test)

# Step 4: Evaluate the model
accuracy6 = accuracy_score(y6_test, y_pred6_test)
print(f'Accuracy For Binary Classification Model using XGBoost: {accuracy6 * 100:.2f}%')

print('Classification Report:')
print(classification_report(y6_test, y_pred6_test))

print('Confusion Matrix:')
print(confusion_matrix(y6_test, y_pred6_test))



Accuracy For Binary Classification Model using XGBoost: 97.73%
Classification Report:
              precision    recall  f1-score   support

           0       0.99      0.99      0.99     18118
           1       0.94      0.93      0.93      3774

    accuracy                           0.98     21892
   macro avg       0.96      0.96      0.96     21892
weighted avg       0.98      0.98      0.98     21892

Confusion Matrix:
[[17876   242]
 [  255  3519]]


**Work For Multi Classification Model**

In [16]:
train_data4 = pd.read_csv(r'/kaggle/input/heartbeat/mitbih_train.csv',header=None)
train_data4.head()

0         1         2         3         4         5         6    \
0  0.977941  0.926471  0.681373  0.245098  0.154412  0.191176  0.151961   
1  0.960114  0.863248  0.461538  0.196581  0.094017  0.125356  0.099715   
2  1.000000  0.659459  0.186486  0.070270  0.070270  0.059459  0.056757   
3  0.925414  0.665746  0.541436  0.276243  0.196133  0.077348  0.071823   
4  0.967136  1.000000  0.830986  0.586854  0.356808  0.248826  0.145540   

        7         8         9    ...  178  179  180  181  182  183  184  185  \
0  0.085784  0.058824  0.049020  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
1  0.088319  0.074074  0.082621  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
2  0.043243  0.054054  0.045946  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
3  0.060773  0.066298  0.058011  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
4  0.089202  0.117371  0.150235  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

   186  187  
0  0.0  0.0  
1  0.0  0.0  
2  0.0  0.0  
3  0.0  0.0  
4  0.0  0.0  

[5 rows x 188 columns]

In [17]:
test_data4 = pd.read_csv(r'/kaggle/input/heartbeat/mitbih_test.csv',header=None)
test_data4.head()

0         1         2         3         4         5         6    \
0  1.000000  0.758264  0.111570  0.000000  0.080579  0.078512  0.066116   
1  0.908425  0.783883  0.531136  0.362637  0.366300  0.344322  0.333333   
2  0.730088  0.212389  0.000000  0.119469  0.101770  0.101770  0.110619   
3  1.000000  0.910417  0.681250  0.472917  0.229167  0.068750  0.000000   
4  0.570470  0.399329  0.238255  0.147651  0.000000  0.003356  0.040268   

        7         8         9    ...  178  179  180  181  182  183  184  185  \
0  0.049587  0.047521  0.035124  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
1  0.307692  0.296703  0.300366  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
2  0.123894  0.115044  0.132743  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
3  0.004167  0.014583  0.054167  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
4  0.080537  0.070470  0.090604  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

   186  187  
0  0.0  0.0  
1  0.0  0.0  
2  0.0  0.0  
3  0.0  0.0  
4  0.0  0.0  

[5 rows x 188 columns]

In [18]:
# Assuming train_data_4 is a Pandas DataFrame
# Remove rows where column 187 has the value 0
train_data4 = train_data4[train_data4[187] != 0]

# Reset the index (optional, for a clean DataFrame)
train_data4.reset_index(drop=True, inplace=True)

# Display the filtered data
train_data4.head()


0         1         2         3         4         5         6    \
0  1.000000  0.666667  0.100457  0.036530  0.073059  0.050228  0.018265   
1  0.983696  1.000000  0.331522  0.000000  0.108696  0.163043  0.130435   
2  1.000000  0.911504  0.216814  0.000000  0.101770  0.199115  0.176991   
3  0.090498  0.126697  0.217195  0.361991  0.461538  0.556561  0.443439   
4  0.961111  1.000000  0.551852  0.101852  0.040741  0.085185  0.094444   

        7         8         9    ...       178       179       180       181  \
0  0.105023  0.132420  0.091324  ...  0.000000  0.000000  0.000000  0.000000   
1  0.190217  0.288043  0.222826  ...  0.461957  0.483696  0.500000  0.494565   
2  0.194690  0.252212  0.238938  ...  0.000000  0.000000  0.000000  0.000000   
3  0.434389  0.452489  0.511312  ...  0.122172  0.131222  0.140271  0.158371   
4  0.088889  0.085185  0.070370  ...  0.000000  0.000000  0.000000  0.000000   

        182      183       184       185       186  187  
0  0.000000  0.00000  0.000000  0.000000  0.000000  1.0  
1  0.510870  0.51087  0.505435  0.472826  0.434783  1.0  
2  0.000000  0.00000  0.000000  0.000000  0.000000  1.0  
3  0.176471  0.20362  0.212670  0.000000  0.000000  1.0  
4  0.000000  0.00000  0.000000  0.000000  0.000000  1.0  

[5 rows x 188 columns]

In [19]:
# Assuming Test_data_4 is a Pandas DataFrame
# Remove rows where column 187 has the value 0
test_data4 = test_data4[test_data4[187] != 0]

# Reset the index (optional, for a clean DataFrame)
test_data4.reset_index(drop=True, inplace=True)

# Display the filtered data
test_data4.head()

0         1         2         3         4         5         6    \
0  1.000000  0.758982  0.473054  0.193114  0.142216  0.176647  0.161677   
1  1.000000  0.746556  0.088154  0.035813  0.212121  0.253444  0.269972   
2  0.972840  0.728395  0.000000  0.037037  0.162963  0.143210  0.123457   
3  1.000000  0.694444  0.238095  0.321429  0.337302  0.337302  0.301587   
4  0.939815  0.791667  0.199074  0.000000  0.055556  0.101852  0.106481   

        7         8         9    ...  178  179  180  181  182  183  184  185  \
0  0.142216  0.121257  0.107784  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
1  0.283747  0.275482  0.272727  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
2  0.140741  0.133333  0.096296  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
3  0.325397  0.325397  0.333333  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
4  0.143519  0.222222  0.189815  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

   186  187  
0  0.0  1.0  
1  0.0  1.0  
2  0.0  1.0  
3  0.0  1.0  
4  0.0  1.0  

[5 rows x 188 columns]

In [23]:
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from imblearn.over_sampling import SMOTE

# Step 1: Prepare features (X) and target (y)
X7 = train_data4.drop(187, axis=1)  # Replace with the appropriate column name
y7 = train_data4[187]

# Splitting the dataset
X_train7, X_test7, y_train7, y_test7 = train_test_split(X7, y7, test_size=0.3, random_state=42)

# Apply SMOTE to the training data
smote = SMOTE(random_state=42)
X_train7_balanced, y_train7_balanced = smote.fit_resample(X_train7, y_train7)

# Check class distribution after SMOTE
print("Class distribution after SMOTE:")
print(y_train7_balanced.value_counts())

# Initialize KNN with k=1
knn = KNeighborsClassifier(n_neighbors=1)

# Train the model
knn.fit(X_train7_balanced, y_train7_balanced)

# Predicting
y_pred7 = knn.predict(X_test7)

# Evaluate accuracy
accuracy = accuracy_score(y_test7, y_pred7)
print("Accuracy: {:.2f}%".format(accuracy * 100))

# Add classification report
print("\nClassification Report:")
print(classification_report(y_test7, y_pred7))

# Add confusion matrix
print("\nConfusion Matrix:")
print(confusion_matrix(y_test7, y_pred7))


Class distribution after SMOTE:
187
2.0    4531
4.0    4531
1.0    4531
3.0    4531
Name: count, dtype: int64
Accuracy: 96.00%

Classification Report:
              precision    recall  f1-score   support

         1.0       0.94      0.94      0.94       658
         2.0       0.96      0.96      0.96      1758
         3.0       0.80      0.85      0.83       209
         4.0       0.99      0.98      0.98      1900

    accuracy                           0.96      4525
   macro avg       0.92      0.93      0.93      4525
weighted avg       0.96      0.96      0.96      4525


Confusion Matrix:
[[ 621   18    9   10]
 [  26 1684   32   16]
 [   7   24  178    0]
 [  10   26    3 1861]]


In [28]:
# Step 1: Prepare features (X) and target (y)
X7_test = test_data4.drop(187, axis=1)  # Replace with the appropriate column name
y7_test = test_data4[187]

# Step 5: Make predictions
y_pred7_test = knn.predict(X7_test)

# Step 6: Evaluate the model
accuracy7 = accuracy_score(y7_test, y_pred7_test)
print(f'Accuracy For Binary Classification Model using XGBoost: {accuracy7 * 100:.2f}%')

print('Classification Report:')
print(classification_report(y7_test, y_pred7_test))

print('Confusion Matrix:')
print(confusion_matrix(y7_test, y_pred7_test))

Accuracy For Binary Classification Model using XGBoost: 95.31%
Classification Report:
              precision    recall  f1-score   support

         1.0       0.93      0.90      0.91       556
         2.0       0.95      0.95      0.95      1448
         3.0       0.74      0.88      0.81       162
         4.0       0.99      0.98      0.98      1608

    accuracy                           0.95      3774
   macro avg       0.90      0.93      0.91      3774
weighted avg       0.95      0.95      0.95      3774

Confusion Matrix:
[[ 499   35   11   11]
 [  26 1380   32   10]
 [   3   15  143    1]
 [   9   17    7 1575]]


In [25]:
from sklearn.ensemble import RandomForestClassifier

# Step 1: Prepare features (X) and target (y)
X8 = train_data4.drop(187, axis=1)  # Replace with the appropriate column name
y8 = train_data4[187]

# Splitting the dataset
X_train8, X_test8, y_train8, y_test8 = train_test_split(X8, y8, test_size=0.3, random_state=42)

# Apply SMOTE to the training data
smote = SMOTE(random_state=42)
X_train8_balanced, y_train8_balanced = smote.fit_resample(X_train8, y_train8)

# Check class distribution after SMOTE
print("Class distribution after SMOTE:")
print(y_train8_balanced.value_counts())

# Initialize Random Forest
rf = RandomForestClassifier(n_estimators=100, random_state=42)

# Train the model
rf.fit(X_train8_balanced, y_train8_balanced)

# Predicting
y_pred8 = rf.predict(X_test8)

# Evaluate accuracy
accuracy8 = accuracy_score(y_test8, y_pred8)
print("Accuracy: {:.2f}%".format(accuracy8 * 100))

# Add classification report
print("\nClassification Report:")
print(classification_report(y_test8, y_pred8))

# Add confusion matrix
print("\nConfusion Matrix:")
print(confusion_matrix(y_test8, y_pred8))

Class distribution after SMOTE:
187
2.0    4531
4.0    4531
1.0    4531
3.0    4531
Name: count, dtype: int64
Accuracy: 97.30%

Classification Report:
              precision    recall  f1-score   support

         1.0       0.94      0.97      0.95       658
         2.0       0.97      0.97      0.97      1758
         3.0       0.92      0.85      0.89       209
         4.0       0.99      0.99      0.99      1900

    accuracy                           0.97      4525
   macro avg       0.96      0.95      0.95      4525
weighted avg       0.97      0.97      0.97      4525


Confusion Matrix:
[[ 637   10    3    8]
 [  19 1713   12   14]
 [  12   19  178    0]
 [   9   16    0 1875]]


In [29]:
# Step 1: Prepare features (X) and target (y)
X8_test = test_data4.drop(187, axis=1)  # Replace with the appropriate column name
y8_test = test_data4[187]

# Step 5: Make predictions
y_pred8_test = rf.predict(X8_test)

# Step 6: Evaluate the model
accuracy8 = accuracy_score(y8_test, y_pred8_test)
print(f'Accuracy For Binary Classification Model using XGBoost: {accuracy8 * 100:.2f}%')

print('Classification Report:')
print(classification_report(y8_test, y_pred8_test))

print('Confusion Matrix:')
print(confusion_matrix(y8_test, y_pred8_test))

Accuracy For Binary Classification Model using XGBoost: 96.66%
Classification Report:
              precision    recall  f1-score   support

         1.0       0.95      0.94      0.94       556
         2.0       0.96      0.97      0.97      1448
         3.0       0.81      0.85      0.83       162
         4.0       0.99      0.98      0.99      1608

    accuracy                           0.97      3774
   macro avg       0.93      0.94      0.93      3774
weighted avg       0.97      0.97      0.97      3774

Confusion Matrix:
[[ 521   19   11    5]
 [  13 1408   20    7]
 [   6   18  138    0]
 [   7   19    1 1581]]


In [97]:
from sklearn.model_selection import train_test_split
from imblearn.over_sampling import SMOTE
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import joblib

# Step 1: Prepare features (X) and target (y)
X9 = train_data4.drop(187, axis=1)  # Replace with the appropriate column name
y9 = train_data4[187]

# Normalize the target (if needed)
y9 = y9 - y9.min()

# Splitting the dataset
X_train9, X_test9, y_train9, y_test9 = train_test_split(X9, y9, test_size=0.3, random_state=42)

# Apply SMOTE to balance the dataset manually
smote = SMOTE(random_state=42)
X_train_resampled, y_train_resampled = smote.fit_resample(X_train9, y_train9)

# Initialize XGBoost Classifier
xgb = XGBClassifier(n_estimators=100, learning_rate=0.1, max_depth=6, random_state=42)

# Train the model with resampled data
xgb.fit(X_train_resampled, y_train_resampled)

# Predicting
y_pred9 = xgb.predict(X_test9)

# Evaluate accuracy
accuracy9 = accuracy_score(y_test9, y_pred9)
print("Accuracy: {:.2f}%".format(accuracy9 * 100))

# Add classification report
print("\nClassification Report:")
print(classification_report(y_test9, y_pred9))

# Add confusion matrix
print("\nConfusion Matrix:")
print(confusion_matrix(y_test9, y_pred9))

# Save the model
joblib.dump(xgb, '/kaggle/working/xgboost_MultiClasses_model.pkl')

print("Model saved as 'xgboost_model.pkl' in /kaggle/working/")


Accuracy: 97.35%

Classification Report:
              precision    recall  f1-score   support

         0.0       0.95      0.97      0.96       658
         1.0       0.98      0.97      0.97      1758
         2.0       0.89      0.88      0.88       209
         3.0       0.99      0.99      0.99      1900

    accuracy                           0.97      4525
   macro avg       0.95      0.95      0.95      4525
weighted avg       0.97      0.97      0.97      4525


Confusion Matrix:
[[ 637    9    5    7]
 [  18 1710   17   13]
 [   5   17  184    3]
 [  10   15    1 1874]]


In [98]:
import joblib
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Load the trained model from the .pkl file
xgb_model = joblib.load('/kaggle/working/xgboost_MultiClasses_model.pkl')

# Step 1: Prepare features (X) and target (y) from the test dataset
X9_test = test_data4.drop(187, axis=1)  # Replace with the appropriate column name
y9_test = test_data4[187]

# Normalize the target (if needed)
y9_test = y9_test - y9_test.min()

# Step 2: Make predictions using the loaded model
y_pred9_test = xgb_model.predict(X9_test)

# Step 3: Evaluate the model
accuracy9 = accuracy_score(y9_test, y_pred9_test)
print(f'Accuracy For Binary Classification Model using XGBoost: {accuracy9 * 100:.2f}%')

# Classification report
print('Classification Report:')
print(classification_report(y9_test, y_pred9_test))

# Confusion matrix
print('Confusion Matrix:')
print(confusion_matrix(y9_test, y_pred9_test))


Accuracy For Binary Classification Model using XGBoost: 96.71%
Classification Report:
              precision    recall  f1-score   support

         0.0       0.95      0.93      0.94       556
         1.0       0.96      0.97      0.97      1448
         2.0       0.81      0.90      0.85       162
         3.0       0.99      0.99      0.99      1608

    accuracy                           0.97      3774
   macro avg       0.93      0.95      0.94      3774
weighted avg       0.97      0.97      0.97      3774

Confusion Matrix:
[[ 519   22   10    5]
 [  16 1401   22    9]
 [   1   15  146    0]
 [   8   14    2 1584]]
